# Generated by Django 3.2 on 2022-09-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='QR',
            field=models.CharField(max_length=100),
        ),
    ]
